name: cross_local_storage_example
description: Demonstrates how to use the cross_local_storage package.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_local_storage:
    path: ../

flutter:
  uses-material-design: true
